trilinos: freeze develop to a working snapshot - i.e a88abd0973ec8715ca5638882daf4c7bf176a133
927a515bcb01461f33901f478d9fc258d113dd4b broke build with:


/gpfs/mira-home/balay/spack/var/spack/stage/trilinos-develop-messzzu2hmnnbz7kb6kw3d7e62awket5/Trilinos/packages/belos/xpetra/src/Belos_Detai
ls_Xpetra_registerSolverFactory.cpp:61:41: fatal error: TpetraCore_ETIHelperMacros.h: No such file or directory
 # include <TpetraCore_ETIHelperMacros.h>
                                         ^